/**
 * The curated tier: the foods people actually log, resolved against USDA SR Legacy / Foundation by
 * description prefix. `name` is what the app shows; `serv` overrides USDA portions when they are odd.
 * Order within a category = popularity. Categories are the app's browse groups.
 */
export const CATEGORIES = [
  { id: 'protein', label: 'Meat, fish & eggs', symbol: 'fish.fill' },
  { id: 'dairy', label: 'Dairy', symbol: 'cup.and.saucer.fill' },
  { id: 'grains', label: 'Grains & bread', symbol: 'leaf.fill' },
  { id: 'fruit', label: 'Fruit', symbol: 'apple.logo' },
  { id: 'vegetables', label: 'Vegetables', symbol: 'carrot.fill' },
  { id: 'legumes', label: 'Legumes & soy', symbol: 'circle.grid.2x2.fill' },
  { id: 'nuts', label: 'Nuts & seeds', symbol: 'circle.hexagongrid.fill' },
  { id: 'fats', label: 'Oils & condiments', symbol: 'drop.fill' },
  { id: 'drinks', label: 'Drinks', symbol: 'mug.fill' },
  { id: 'snacks', label: 'Snacks & sweets', symbol: 'birthday.cake.fill' },
  { id: 'prepared', label: 'Meals & fast food', symbol: 'takeoutbag.and.cup.and.straw.fill' },
  { id: 'supplements', label: 'Supplements', symbol: 'pills.fill' },
  { id: 'other', label: 'Other', symbol: 'basket.fill' },
];

const g = (label, grams) => ({ label, grams });

export const CURATED = [
  // ---- protein --------------------------------------------------------------------------------
  { q: 'Chicken, broilers or fryers, breast, meat only, cooked, roasted', name: 'Chicken breast, roasted', cat: 'protein', tags: ['chicken', 'poultry', 'grilled', 'baked', 'skinless'], serv: [g('1 breast', 172), g('small portion', 100), g('large portion', 200)] },
  { q: 'Chicken, broilers or fryers, thigh, meat only, cooked, roasted', name: 'Chicken thigh, roasted', cat: 'protein', tags: ['chicken', 'poultry'], serv: [g('1 thigh', 52), g('portion', 120)] },
  { q: 'Chicken, broilers or fryers, drumstick, meat and skin, cooked, roasted', name: 'Chicken drumstick, roasted', cat: 'protein', tags: ['chicken'], serv: [g('1 drumstick', 44), g('2 drumsticks', 88)] },
  { q: 'Chicken, broilers or fryers, breast, meat and skin, cooked, fried, batter', name: 'Fried chicken breast', cat: 'protein', tags: ['chicken', 'fried'] },
  { q: 'Turkey, all classes, breast, meat only, cooked, roasted', alt: 'Turkey, retail parts, breast, meat only, cooked, roasted', name: 'Turkey breast, roasted', cat: 'protein', tags: ['turkey', 'poultry'], serv: [g('portion', 120), g('3 oz', 85)] },
  { q: 'Turkey, ground, 93% lean, 7% fat, pan-broiled crumbles', name: 'Ground turkey 93%, cooked', cat: 'protein', tags: ['turkey'], serv: [g('portion', 120)] },
  { q: 'Beef, ground, 93% lean meat / 7% fat, patty, cooked, broiled', name: 'Ground beef 93% lean, cooked', cat: 'protein', tags: ['beef', 'burger'], serv: [g('1 patty', 85), g('portion', 150)] },
  { q: 'Beef, ground, 85% lean meat / 15% fat, patty, cooked, broiled', name: 'Ground beef 85% lean, cooked', cat: 'protein', tags: ['beef', 'burger'], serv: [g('1 patty', 85), g('portion', 150)] },
  { q: 'Beef, ground, 80% lean meat / 20% fat, patty, cooked, broiled', name: 'Ground beef 80% lean, cooked', cat: 'protein', tags: ['beef', 'burger'], serv: [g('1 patty', 85), g('portion', 150)] },
  { q: 'Beef, top sirloin, steak, separable lean only, trimmed to 1/8" fat, all grades, cooked, broiled', name: 'Sirloin steak, lean', cat: 'protein', tags: ['beef', 'steak'], serv: [g('1 steak', 200), g('portion', 150)] },
  { q: 'Beef, tenderloin, steak, separable lean only, trimmed to 1/8" fat, all grades, cooked, broiled', name: 'Filet mignon, lean', cat: 'protein', tags: ['beef', 'steak'], serv: [g('1 steak', 170)] },
  { q: 'Beef, rib eye steak, boneless, lip-on, separable lean only, trimmed to 1/8" fat, all grades, cooked, grilled', alt: 'Beef, rib eye steak, boneless, lip-on, separable lean only, trimmed to 1/8', name: 'Ribeye steak', cat: 'protein', tags: ['beef', 'steak'], serv: [g('1 steak', 250), g('portion', 170)] },
  { q: 'Beef, chuck, arm pot roast, separable lean only, trimmed to 1/8" fat, all grades, cooked, braised', name: 'Beef pot roast, lean', cat: 'protein', tags: ['beef'], serv: [g('portion', 150)] },
  { q: 'Beef, cured, corned beef, brisket, cooked', name: 'Corned beef', cat: 'protein', tags: ['beef'] },
  { q: 'Pork, fresh, loin, tenderloin, separable lean only, cooked, roasted', name: 'Pork tenderloin, roasted', cat: 'protein', tags: ['pork'], serv: [g('portion', 120)] },
  { q: 'Pork, fresh, loin, center loin (chops), bone-in, separable lean only, cooked, broiled', name: 'Pork chop, lean', cat: 'protein', tags: ['pork'], serv: [g('1 chop', 130)] },
  { q: 'Pork, cured, bacon, cooked, baked', name: 'Bacon, cooked', cat: 'protein', tags: ['pork', 'breakfast'], serv: [g('1 slice', 8), g('2 slices', 16), g('3 slices', 24)] },
  { q: 'Pork, cured, ham, boneless, extra lean (approximately 5% fat), roasted', name: 'Ham, extra lean', cat: 'protein', tags: ['pork', 'deli'], serv: [g('1 slice', 28), g('portion', 85)] },
  { q: 'Sausage, Italian, pork, mild, cooked, pan-fried', name: 'Italian sausage, cooked', cat: 'protein', tags: ['pork', 'sausage'], serv: [g('1 link', 83)] },
  { q: 'Frankfurter, beef, unheated', alt: 'Frankfurter, beef', name: 'Beef hot dog', cat: 'protein', tags: ['beef'], serv: [g('1 frank', 57)] },
  { q: 'Lamb, leg, shank half, separable lean only, trimmed to 1/4', name: 'Lamb leg, roasted', cat: 'protein', tags: ['lamb'], serv: [g('portion', 120)] },
  { q: 'Fish, salmon, Atlantic, farmed, cooked, dry heat', name: 'Salmon, cooked', cat: 'protein', tags: ['fish', 'salmon', 'omega-3', 'grilled', 'baked', 'fillet'], serv: [g('1 fillet', 154), g('portion', 120)] },
  { q: 'Fish, salmon, sockeye, cooked, dry heat', name: 'Sockeye salmon, cooked', cat: 'protein', tags: ['fish', 'salmon'], serv: [g('1 fillet', 155), g('portion', 120)] },
  { q: 'Fish, salmon, pink, canned, drained solids', alt: 'Fish, salmon, pink, canned', name: 'Canned salmon', cat: 'protein', tags: ['fish', 'salmon'], serv: [g('½ can', 85)] },
  { q: 'Fish, tuna, light, canned in water, drained solids', name: 'Tuna, canned in water', cat: 'protein', tags: ['fish', 'tuna'], serv: [g('1 can, drained', 120), g('½ can', 60)] },
  { q: 'Fish, tuna, yellowfin, fresh, cooked, dry heat', name: 'Tuna steak, cooked', cat: 'protein', tags: ['fish', 'tuna'], serv: [g('portion', 120)] },
  { q: 'Fish, cod, Atlantic, cooked, dry heat', name: 'Cod, cooked', cat: 'protein', tags: ['fish'], serv: [g('1 fillet', 180), g('portion', 120)] },
  { q: 'Fish, tilapia, cooked, dry heat', name: 'Tilapia, cooked', cat: 'protein', tags: ['fish'], serv: [g('1 fillet', 87), g('portion', 120)] },
  { q: 'Fish, halibut, Atlantic and Pacific, cooked, dry heat', name: 'Halibut, cooked', cat: 'protein', tags: ['fish'], serv: [g('portion', 120)] },
  { q: 'Fish, sardine, Atlantic, canned in oil, drained solids with bone', name: 'Sardines, canned', cat: 'protein', tags: ['fish', 'omega-3'], serv: [g('1 can', 92)] },
  { q: 'Fish, mackerel, Atlantic, cooked, dry heat', name: 'Mackerel, cooked', cat: 'protein', tags: ['fish', 'omega-3'], serv: [g('1 fillet', 88)] },
  { q: 'Crustaceans, shrimp, cooked', alt: 'Crustaceans, shrimp, mixed species, cooked, moist heat', name: 'Shrimp, cooked', cat: 'protein', tags: ['seafood'], serv: [g('6 large', 60), g('portion', 100)] },
  { q: 'Mollusks, scallop, (bay and sea), cooked, steamed', name: 'Scallops, cooked', cat: 'protein', tags: ['seafood'], serv: [g('portion', 100)] },
  { q: 'Crustaceans, crab, blue, cooked, moist heat', name: 'Crab, cooked', cat: 'protein', tags: ['seafood'], serv: [g('portion', 100)] },
  { q: 'Egg, whole, raw, fresh', name: 'Egg, whole', cat: 'protein', tags: ['eggs', 'breakfast', 'fried egg', 'omelette', 'omelet', 'poached'], serv: [g('1 large', 50), g('2 large', 100), g('3 large', 150)] },
  { q: 'Egg, whole, cooked, hard-boiled', name: 'Egg, hard-boiled', cat: 'protein', tags: ['eggs'], serv: [g('1 large', 50), g('2 large', 100)] },
  { q: 'Egg, whole, cooked, scrambled', name: 'Eggs, scrambled', cat: 'protein', tags: ['eggs', 'breakfast'], serv: [g('1 egg', 61), g('2 eggs', 122), g('3 eggs', 183)] },
  { q: 'Egg, white, raw, fresh', name: 'Egg white', cat: 'protein', tags: ['eggs'], serv: [g('1 large white', 33), g('3 whites', 99), g('½ cup liquid', 122)] },
  { q: 'Egg, yolk, raw, fresh', name: 'Egg yolk', cat: 'protein', tags: ['eggs'], serv: [g('1 large yolk', 17)] },
  // ---- dairy ----------------------------------------------------------------------------------
  { q: 'Yogurt, Greek, plain, nonfat', name: 'Greek yogurt, nonfat', cat: 'dairy', tags: ['yogurt', 'breakfast'], serv: [g('1 cup', 245), g('single-serve cup', 170), g('½ cup', 122)] },
  { q: 'Yogurt, Greek, plain, lowfat', name: 'Greek yogurt, 2%', cat: 'dairy', tags: ['yogurt'], serv: [g('1 cup', 245), g('single-serve cup', 170)] },
  { q: 'Yogurt, Greek, plain, whole milk', name: 'Greek yogurt, whole milk', cat: 'dairy', tags: ['yogurt'], serv: [g('1 cup', 245), g('single-serve cup', 170)] },
  { q: 'Yogurt, plain, low fat', name: 'Yogurt, plain low fat', cat: 'dairy', tags: ['yogurt'], serv: [g('1 cup', 245)] },
  { q: 'Cheese, cottage, lowfat, 2% milkfat', name: 'Cottage cheese, 2%', cat: 'dairy', tags: ['cheese'], serv: [g('1 cup', 226), g('½ cup', 113)] },
  { q: 'Cheese, cheddar', name: 'Cheddar cheese', cat: 'dairy', tags: ['cheese'], serv: [g('1 slice', 28), g('1 oz', 28), g('¼ cup shredded', 28)] },
  { q: 'Cheese, mozzarella, part skim milk', name: 'Mozzarella, part skim', cat: 'dairy', tags: ['cheese'], serv: [g('1 oz', 28), g('¼ cup shredded', 28)] },
  { q: 'Cheese, parmesan, grated', name: 'Parmesan, grated', cat: 'dairy', tags: ['cheese'], serv: [g('1 tbsp', 5), g('¼ cup', 20)] },
  { q: 'Cheese, feta', name: 'Feta cheese', cat: 'dairy', tags: ['cheese'], serv: [g('¼ cup crumbled', 38), g('1 oz', 28)] },
  { q: 'Cheese, swiss', name: 'Swiss cheese', cat: 'dairy', tags: ['cheese'], serv: [g('1 slice', 28)] },
  { q: 'Cheese, cream', name: 'Cream cheese', cat: 'dairy', tags: ['cheese'], serv: [g('1 tbsp', 14.5), g('2 tbsp', 29)] },
  { q: 'Milk, whole, 3.25% milkfat, with added vitamin D', name: 'Whole milk', cat: 'dairy', tags: ['milk'], serv: [g('1 cup', 244), g('½ cup', 122)] },
  { q: 'Milk, reduced fat, fluid, 2% milkfat, with added vitamin A and vitamin D', name: 'Milk, 2%', cat: 'dairy', tags: ['milk'], serv: [g('1 cup', 244), g('½ cup', 122)] },
  { q: 'Milk, nonfat, fluid, with added vitamin A and vitamin D (fat free or skim)', name: 'Skim milk', cat: 'dairy', tags: ['milk'], serv: [g('1 cup', 245)] },
  { q: 'Cream, fluid, heavy whipping', name: 'Heavy cream', cat: 'dairy', tags: ['cream'], serv: [g('1 tbsp', 15), g('¼ cup', 60)] },
  { q: 'Cream, fluid, half and half', name: 'Half and half', cat: 'dairy', tags: ['cream', 'coffee'], serv: [g('1 tbsp', 15), g('2 tbsp', 30)] },
  { q: 'Butter, salted', name: 'Butter', cat: 'dairy', tags: ['fat'], serv: [g('1 tbsp', 14), g('1 tsp', 5), g('1 pat', 5)] },
  { q: 'Kefir, lowfat, plain, LIFEWAY', alt: 'Kefir', name: 'Kefir, plain', cat: 'dairy', tags: ['probiotic'], serv: [g('1 cup', 243)] },
  { q: 'Ice creams, vanilla', name: 'Vanilla ice cream', cat: 'snacks', tags: ['dessert'], serv: [g('½ cup', 66), g('1 cup', 132)] },
  // ---- grains ---------------------------------------------------------------------------------
  { q: 'Cereals, oats, regular and quick, not fortified, dry', name: 'Oats, dry', cat: 'grains', tags: ['oatmeal', 'breakfast'], serv: [g('½ cup', 40), g('1 cup', 81)] },
  { q: 'Cereals, oats, regular and quick, unenriched, cooked with water (includes boiling and microwaving), without salt', name: 'Oatmeal, cooked', cat: 'grains', tags: ['oatmeal', 'breakfast'], serv: [g('1 cup', 234), g('1 bowl', 300)] },
  { q: 'Rice, white, long-grain, regular, cooked', name: 'White rice, cooked', cat: 'grains', tags: ['rice', 'jasmine', 'basmati', 'long grain', 'steamed'], serv: [g('1 cup', 158), g('½ cup', 79), g('1 bowl', 250)] },
  { q: 'Rice, brown, long-grain, cooked', name: 'Brown rice, cooked', cat: 'grains', tags: ['rice', 'whole grain', 'brown basmati'], serv: [g('1 cup', 195), g('½ cup', 98)] },
  { q: 'Rice, white, short-grain, cooked', name: 'Sushi rice, cooked', cat: 'grains', tags: ['rice', 'short grain', 'sticky rice', 'calrose'], serv: [g('1 cup', 186)] },
  { q: 'Quinoa, cooked', name: 'Quinoa, cooked', cat: 'grains', tags: [], serv: [g('1 cup', 185), g('½ cup', 93)] },
  { q: 'Pasta, cooked, enriched, without added salt', name: 'Pasta, cooked', cat: 'grains', tags: ['spaghetti', 'noodles', 'penne', 'macaroni', 'linguine', 'fettuccine'], serv: [g('1 cup', 124), g('2 cups', 248)] },
  { q: 'Pasta, whole-wheat, cooked', name: 'Whole-wheat pasta, cooked', cat: 'grains', tags: ['spaghetti'], serv: [g('1 cup', 117)] },
  { q: 'Noodles, egg, cooked, enriched', alt: 'Noodles, egg, cooked', name: 'Egg noodles, cooked', cat: 'grains', tags: ['noodles'], serv: [g('1 cup', 160)] },
  { q: 'Couscous, cooked', name: 'Couscous, cooked', cat: 'grains', tags: [], serv: [g('1 cup', 157)] },
  { q: 'Barley, pearled, cooked', name: 'Barley, cooked', cat: 'grains', tags: [], serv: [g('1 cup', 157)] },
  { q: 'Bulgur, cooked', name: 'Bulgur, cooked', cat: 'grains', tags: [], serv: [g('1 cup', 182)] },
  { q: 'Bread, whole-wheat, commercially prepared', name: 'Whole-wheat bread', cat: 'grains', tags: ['bread', 'toast'], serv: [g('1 slice', 32), g('2 slices', 64)] },
  { q: 'Bread, white, commercially prepared', name: 'White bread', cat: 'grains', tags: ['bread', 'toast'], serv: [g('1 slice', 27), g('2 slices', 54)] },
  { q: 'Bread, pita, whole-wheat', name: 'Pita, whole-wheat', cat: 'grains', tags: ['bread'], serv: [g('1 pita', 64)] },
  { q: 'Bagels, plain, enriched, with calcium propionate (includes onion, poppy, sesame)', alt: 'Bagels, plain', name: 'Bagel, plain', cat: 'grains', tags: ['bread', 'breakfast'], serv: [g('1 bagel', 99)] },
  { q: 'Tortillas, ready-to-bake or -fry, flour', name: 'Flour tortilla', cat: 'grains', tags: ['wrap'], serv: [g('1 medium', 49), g('1 large burrito size', 72)] },
  { q: 'Tortillas, ready-to-bake or -fry, corn', name: 'Corn tortilla', cat: 'grains', tags: ['taco'], serv: [g('1 tortilla', 26), g('2 tortillas', 52)] },
  { q: 'Croissants, butter', name: 'Croissant', cat: 'grains', tags: ['pastry', 'breakfast'], serv: [g('1 croissant', 57)] },
  { q: 'Pancakes, plain, prepared from recipe', name: 'Pancakes', cat: 'grains', tags: ['breakfast'], serv: [g('1 pancake', 38), g('3 pancakes', 114)] },
  { q: 'Waffles, plain, prepared from recipe', name: 'Waffle', cat: 'grains', tags: ['breakfast'], serv: [g('1 waffle', 75)] },
  { q: 'Cereals ready-to-eat, granola, homemade', alt: 'Cereals ready-to-eat, granola', name: 'Granola', cat: 'grains', tags: ['breakfast', 'cereal'], serv: [g('½ cup', 61), g('¼ cup', 30)] },
  { q: 'Crackers, whole-wheat', name: 'Whole-wheat crackers', cat: 'snacks', tags: ['crackers'], serv: [g('5 crackers', 20)] },
  { q: 'Potatoes, baked, flesh and skin, without salt', name: 'Baked potato', cat: 'vegetables', tags: ['potato', 'starch'], serv: [g('1 medium', 173), g('1 large', 299)] },
  { q: 'Potatoes, mashed, home-prepared, whole milk and butter added', alt: 'Potatoes, mashed', name: 'Mashed potatoes', cat: 'vegetables', tags: ['potato'], serv: [g('1 cup', 210)] },
  { q: 'Sweet potato, cooked, baked in skin, flesh, without salt', name: 'Sweet potato, baked', cat: 'vegetables', tags: ['potato', 'starch'], serv: [g('1 medium', 114), g('1 large', 180)] },
  // ---- fruit ----------------------------------------------------------------------------------
  { q: 'Bananas, raw', name: 'Banana', cat: 'fruit', tags: [], serv: [g('1 medium', 118), g('1 large', 136), g('1 small', 101)] },
  { q: 'Apples, raw, with skin', name: 'Apple', cat: 'fruit', tags: [], serv: [g('1 medium', 182), g('1 large', 223)] },
  { q: 'Oranges, raw, all commercial varieties', name: 'Orange', cat: 'fruit', tags: [], serv: [g('1 medium', 131)] },
  { q: 'Strawberries, raw', name: 'Strawberries', cat: 'fruit', tags: ['berries'], serv: [g('1 cup', 152), g('5 berries', 60)] },
  { q: 'Blueberries, raw', name: 'Blueberries', cat: 'fruit', tags: ['berries'], serv: [g('1 cup', 148), g('½ cup', 74)] },
  { q: 'Raspberries, raw', name: 'Raspberries', cat: 'fruit', tags: ['berries'], serv: [g('1 cup', 123)] },
  { q: 'Grapes, red or green (European type, such as Thompson seedless), raw', name: 'Grapes', cat: 'fruit', tags: [], serv: [g('1 cup', 151), g('10 grapes', 49)] },
  { q: 'Watermelon, raw', name: 'Watermelon', cat: 'fruit', tags: [], serv: [g('1 cup diced', 152), g('1 wedge', 286)] },
  { q: 'Pineapple, raw, all varieties', name: 'Pineapple', cat: 'fruit', tags: [], serv: [g('1 cup chunks', 165)] },
  { q: 'Mangos, raw', name: 'Mango', cat: 'fruit', tags: [], serv: [g('1 cup pieces', 165), g('1 mango', 336)] },
  { q: 'Peaches, yellow, raw', name: 'Peach', cat: 'fruit', tags: [], serv: [g('1 medium', 150)] },
  { q: 'Pears, raw', name: 'Pear', cat: 'fruit', tags: [], serv: [g('1 medium', 178)] },
  { q: 'Cherries, sweet, raw', name: 'Cherries', cat: 'fruit', tags: [], serv: [g('1 cup', 154)] },
  { q: 'Kiwifruit, green, raw', name: 'Kiwi', cat: 'fruit', tags: [], serv: [g('1 fruit', 69)] },
  { q: 'Avocados, raw, all commercial varieties', name: 'Avocado', cat: 'fruit', tags: ['healthy fat'], serv: [g('½ avocado', 68), g('1 avocado', 136), g('¼ avocado', 34)] },
  { q: 'Lemons, raw, without peel', name: 'Lemon', cat: 'fruit', tags: [], serv: [g('1 lemon', 58), g('juice of 1 lemon', 47)] },
  { q: 'Dates, medjool', name: 'Medjool dates', cat: 'fruit', tags: ['dried'], serv: [g('1 date', 24), g('3 dates', 72)] },
  { q: 'Raisins, dark, seedless', name: 'Raisins', cat: 'fruit', tags: ['dried'], serv: [g('small box', 43), g('¼ cup', 41)] },
  { q: 'Applesauce, canned, unsweetened, without added ascorbic acid', alt: 'Applesauce, canned, unsweetened', name: 'Applesauce, unsweetened', cat: 'fruit', tags: [], serv: [g('1 cup', 244), g('single-serve cup', 113)] },
  // ---- vegetables -----------------------------------------------------------------------------
  { q: 'Broccoli, cooked, boiled, drained, without salt', name: 'Broccoli, cooked', cat: 'vegetables', tags: [], serv: [g('1 cup', 156), g('½ cup', 78)] },
  { q: 'Spinach, raw', name: 'Spinach, raw', cat: 'vegetables', tags: ['greens', 'salad'], serv: [g('1 cup', 30), g('2 cups', 60)] },
  { q: 'Spinach, cooked, boiled, drained, without salt', name: 'Spinach, cooked', cat: 'vegetables', tags: ['greens'], serv: [g('1 cup', 180)] },
  { q: 'Kale, raw', name: 'Kale, raw', cat: 'vegetables', tags: ['greens', 'salad'], serv: [g('1 cup chopped', 21), g('2 cups', 42)] },
  { q: 'Lettuce, cos or romaine, raw', name: 'Romaine lettuce', cat: 'vegetables', tags: ['salad'], serv: [g('1 cup shredded', 47), g('2 cups', 94)] },
  { q: 'Carrots, raw', name: 'Carrots, raw', cat: 'vegetables', tags: [], serv: [g('1 medium', 61), g('1 cup chopped', 128), g('10 baby carrots', 100)] },
  { q: 'Tomatoes, red, ripe, raw, year round average', name: 'Tomato', cat: 'vegetables', tags: ['salad'], serv: [g('1 medium', 123), g('1 cup chopped', 180)] },
  { q: 'Cucumber, with peel, raw', name: 'Cucumber', cat: 'vegetables', tags: ['salad'], serv: [g('1 cup sliced', 104), g('½ cucumber', 150)] },
  { q: 'Onions, raw', name: 'Onion, raw', cat: 'vegetables', tags: [], serv: [g('1 medium', 110), g('½ cup chopped', 80)] },
  { q: 'Peppers, sweet, red, raw', name: 'Red bell pepper', cat: 'vegetables', tags: [], serv: [g('1 medium', 119), g('1 cup chopped', 149)] },
  { q: 'Mushrooms, white, raw', name: 'Mushrooms, raw', cat: 'vegetables', tags: [], serv: [g('1 cup sliced', 70)] },
  { q: 'Asparagus, cooked, boiled, drained', name: 'Asparagus, cooked', cat: 'vegetables', tags: [], serv: [g('6 spears', 90), g('1 cup', 180)] },
  { q: 'Cauliflower, cooked, boiled, drained, without salt', name: 'Cauliflower, cooked', cat: 'vegetables', tags: [], serv: [g('1 cup', 124)] },
  { q: 'Brussels sprouts, cooked, boiled, drained, without salt', name: 'Brussels sprouts, cooked', cat: 'vegetables', tags: [], serv: [g('1 cup', 156)] },
  { q: 'Beans, snap, green, cooked, boiled, drained, without salt', name: 'Green beans, cooked', cat: 'vegetables', tags: [], serv: [g('1 cup', 125)] },
  { q: 'Corn, sweet, yellow, cooked, boiled, drained, without salt', name: 'Sweet corn, cooked', cat: 'vegetables', tags: [], serv: [g('1 ear', 103), g('1 cup', 149)] },
  { q: 'Peas, green, cooked, boiled, drained, without salt', name: 'Green peas, cooked', cat: 'vegetables', tags: [], serv: [g('1 cup', 160), g('½ cup', 80)] },
  { q: 'Squash, summer, zucchini, includes skin, cooked, boiled, drained, without salt', name: 'Zucchini, cooked', cat: 'vegetables', tags: [], serv: [g('1 cup', 180)] },
  { q: 'Celery, raw', name: 'Celery', cat: 'vegetables', tags: [], serv: [g('1 stalk', 40), g('1 cup chopped', 101)] },
  { q: 'Beets, cooked, boiled, drained', name: 'Beets, cooked', cat: 'vegetables', tags: [], serv: [g('1 cup', 170)] },
  { q: 'Garlic, raw', name: 'Garlic', cat: 'vegetables', tags: [], serv: [g('1 clove', 3), g('3 cloves', 9)] },
  { q: 'Cabbage, raw', name: 'Cabbage, raw', cat: 'vegetables', tags: ['salad'], serv: [g('1 cup shredded', 70)] },
  { q: 'Edamame, frozen, prepared', name: 'Edamame', cat: 'legumes', tags: ['soy'], serv: [g('1 cup shelled', 155), g('½ cup', 78)] },
  // ---- legumes & soy --------------------------------------------------------------------------
  { q: 'Lentils, mature seeds, cooked, boiled, without salt', name: 'Lentils, cooked', cat: 'legumes', tags: [], serv: [g('1 cup', 198), g('½ cup', 99)] },
  { q: 'Chickpeas (garbanzo beans, bengal gram), mature seeds, cooked, boiled, without salt', name: 'Chickpeas, cooked', cat: 'legumes', tags: ['garbanzo'], serv: [g('1 cup', 164), g('½ cup', 82)] },
  { q: 'Beans, black, mature seeds, cooked, boiled, without salt', name: 'Black beans, cooked', cat: 'legumes', tags: [], serv: [g('1 cup', 172), g('½ cup', 86)] },
  { q: 'Beans, kidney, all types, mature seeds, cooked, boiled, without salt', name: 'Kidney beans, cooked', cat: 'legumes', tags: [], serv: [g('1 cup', 177)] },
  { q: 'Beans, pinto, mature seeds, cooked, boiled, without salt', name: 'Pinto beans, cooked', cat: 'legumes', tags: [], serv: [g('1 cup', 171)] },
  { q: 'Hummus, commercial', name: 'Hummus', cat: 'legumes', tags: ['dip'], serv: [g('2 tbsp', 30), g('¼ cup', 60)] },
  { q: 'Tofu, firm, prepared with calcium sulfate and magnesium chloride (nigari)', alt: 'Tofu, firm, prepared with calcium sulfate', name: 'Tofu, firm', cat: 'legumes', tags: ['soy', 'vegan'], serv: [g('½ block', 126), g('portion', 150)] },
  { q: 'Tempeh', name: 'Tempeh', cat: 'legumes', tags: ['soy', 'vegan'], serv: [g('portion', 100)] },
  { q: 'Soymilk, original and vanilla, unfortified', alt: 'Soymilk', name: 'Soy milk', cat: 'drinks', tags: ['milk', 'vegan'], serv: [g('1 cup', 243)] },
  // ---- nuts & seeds ---------------------------------------------------------------------------
  { q: 'Nuts, almonds', name: 'Almonds', cat: 'nuts', tags: [], serv: [g('1 oz (23 nuts)', 28), g('¼ cup', 36), g('10 almonds', 12)] },
  { q: 'Nuts, walnuts, english', name: 'Walnuts', cat: 'nuts', tags: ['omega-3'], serv: [g('1 oz (14 halves)', 28), g('¼ cup', 29)] },
  { q: 'Nuts, cashew nuts, dry roasted, without salt added', alt: 'Nuts, cashew nuts, dry roasted', name: 'Cashews', cat: 'nuts', tags: [], serv: [g('1 oz (18 nuts)', 28), g('¼ cup', 34)] },
  { q: 'Nuts, pistachio nuts, dry roasted, without salt added', alt: 'Nuts, pistachio nuts, dry roasted', name: 'Pistachios', cat: 'nuts', tags: [], serv: [g('1 oz (49 kernels)', 28)] },
  { q: 'Peanuts, all types, dry-roasted, without salt', alt: 'Peanuts, all types, dry-roasted', name: 'Peanuts, roasted', cat: 'nuts', tags: [], serv: [g('1 oz', 28), g('¼ cup', 37)] },
  { q: 'Peanut butter, smooth style, with salt', name: 'Peanut butter', cat: 'nuts', tags: ['spread'], serv: [g('1 tbsp', 16), g('2 tbsp', 32)] },
  { q: 'Nuts, almond butter, plain, without salt added', alt: 'Nuts, almond butter, plain', name: 'Almond butter', cat: 'nuts', tags: ['spread'], serv: [g('1 tbsp', 16), g('2 tbsp', 32)] },
  { q: 'Seeds, chia seeds, dried', name: 'Chia seeds', cat: 'nuts', tags: ['omega-3', 'fiber'], serv: [g('1 tbsp', 12), g('2 tbsp', 24)] },
  { q: 'Seeds, flaxseed', name: 'Flaxseed', cat: 'nuts', tags: ['omega-3'], serv: [g('1 tbsp ground', 7), g('2 tbsp', 14)] },
  { q: 'Seeds, pumpkin and squash seed kernels, dried', name: 'Pumpkin seeds', cat: 'nuts', tags: [], serv: [g('1 oz', 28), g('¼ cup', 32)] },
  { q: 'Seeds, sunflower seed kernels, dried', name: 'Sunflower seeds', cat: 'nuts', tags: [], serv: [g('1 oz', 28), g('¼ cup', 35)] },
  { q: 'Nuts, coconut milk, raw (liquid expressed from grated meat and water)', name: 'Coconut milk', cat: 'fats', tags: ['coconut'], serv: [g('½ cup', 120), g('1 cup', 240)] },
  // ---- oils & condiments ----------------------------------------------------------------------
  { q: 'Oil, olive, salad or cooking', name: 'Olive oil', cat: 'fats', tags: ['oil'], serv: [g('1 tbsp', 13.5), g('1 tsp', 4.5)] },
  { q: 'Oil, coconut', name: 'Coconut oil', cat: 'fats', tags: ['oil'], serv: [g('1 tbsp', 13.6), g('1 tsp', 4.5)] },
  { q: 'Oil, canola', name: 'Canola oil', cat: 'fats', tags: ['oil'], serv: [g('1 tbsp', 14), g('1 tsp', 4.5)] },
  { q: 'Oil, avocado', name: 'Avocado oil', cat: 'fats', tags: ['oil'], serv: [g('1 tbsp', 14)] },
  { q: 'Salad dressing, mayonnaise, regular', name: 'Mayonnaise', cat: 'fats', tags: ['condiment'], serv: [g('1 tbsp', 13.8), g('2 tbsp', 28)] },
  { q: 'Catsup', name: 'Ketchup', cat: 'fats', tags: ['condiment'], serv: [g('1 tbsp', 17), g('2 tbsp', 34)] },
  { q: 'Mustard, prepared, yellow', name: 'Mustard', cat: 'fats', tags: ['condiment'], serv: [g('1 tsp', 5), g('1 tbsp', 15)] },
  { q: 'Salad dressing, ranch dressing, regular', name: 'Ranch dressing', cat: 'fats', tags: ['condiment', 'salad'], serv: [g('2 tbsp', 30)] },
  { q: 'Soy sauce made from soy and wheat (shoyu)', alt: 'Soy sauce made from soy and wheat', name: 'Soy sauce', cat: 'fats', tags: ['condiment'], serv: [g('1 tbsp', 16)] },
  { q: 'Salsa, ready-to-serve', alt: 'Sauce, salsa, ready-to-serve', name: 'Salsa', cat: 'fats', tags: ['condiment'], serv: [g('2 tbsp', 36), g('¼ cup', 72)] },
  { q: 'Honey', name: 'Honey', cat: 'fats', tags: ['sweetener'], serv: [g('1 tbsp', 21), g('1 tsp', 7)] },
  { q: 'Syrups, maple', name: 'Maple syrup', cat: 'fats', tags: ['sweetener'], serv: [g('1 tbsp', 20), g('¼ cup', 80)] },
  { q: 'Sugars, granulated', name: 'Sugar, white', cat: 'fats', tags: ['sweetener'], serv: [g('1 tsp', 4.2), g('1 tbsp', 12.6)] },
  { q: 'Jams and preserves', name: 'Jam', cat: 'fats', tags: ['spread'], serv: [g('1 tbsp', 20)] },
  // ---- drinks ---------------------------------------------------------------------------------
  { q: 'Beverages, coffee, brewed, prepared with tap water', name: 'Coffee, black', cat: 'drinks', tags: ['coffee', 'caffeine', 'americano', 'drip', 'cold brew'], serv: [g('1 cup', 237), g('1 mug', 355)] },
  { q: 'Beverages, coffee, brewed, espresso, restaurant-prepared', name: 'Espresso', cat: 'drinks', tags: ['coffee', 'caffeine'], serv: [g('1 shot', 30), g('double shot', 60)] },
  { q: 'Beverages, tea, green, brewed, regular', name: 'Green tea', cat: 'drinks', tags: ['tea'], serv: [g('1 cup', 245)] },
  { q: 'Beverages, tea, black, brewed, prepared with tap water', name: 'Black tea', cat: 'drinks', tags: ['tea'], serv: [g('1 cup', 237)] },
  { q: 'Orange juice, raw', name: 'Orange juice', cat: 'drinks', tags: ['juice'], serv: [g('1 cup', 248), g('small glass', 180)] },
  { q: 'Beverages, almond milk, unsweetened, shelf stable', alt: 'Beverages, almond milk, unsweetened', name: 'Almond milk, unsweetened', cat: 'drinks', tags: ['milk', 'vegan'], serv: [g('1 cup', 240)] },
  { q: 'Beverages, Oat milk, unsweetened', alt: 'Oat milk', name: 'Oat milk', cat: 'drinks', tags: ['milk', 'vegan'], serv: [g('1 cup', 240)] },
  { q: 'Beverages, carbonated, cola, regular', alt: 'Beverages, carbonated, cola', name: 'Cola', cat: 'drinks', tags: ['soda'], serv: [g('1 can (12 oz)', 368), g('1 bottle (20 oz)', 613)] },
  { q: 'Beverages, carbonated, low calorie, cola or pepper-type, with aspartame, without caffeine', alt: 'Beverages, carbonated, low calorie, cola', name: 'Diet cola', cat: 'drinks', tags: ['soda'], serv: [g('1 can (12 oz)', 355)] },
  { q: 'Beverages, Energy drink, Monster', alt: 'Beverages, Energy drink', name: 'Energy drink', cat: 'drinks', tags: ['caffeine'], serv: [g('1 can (16 oz)', 480), g('1 can (8.4 oz)', 250)] },
  { q: 'Alcoholic beverage, beer, regular, all', alt: 'Alcoholic beverage, beer, regular', name: 'Beer', cat: 'drinks', tags: ['alcohol'], serv: [g('1 can (12 oz)', 356), g('1 pint', 473)] },
  { q: 'Alcoholic beverage, wine, table, red', name: 'Red wine', cat: 'drinks', tags: ['alcohol'], serv: [g('1 glass (5 oz)', 147)] },
  { q: 'Alcoholic beverage, wine, table, white', name: 'White wine', cat: 'drinks', tags: ['alcohol'], serv: [g('1 glass (5 oz)', 147)] },
  { q: 'Alcoholic beverage, distilled, all (gin, rum, vodka, whiskey) 80 proof', name: 'Spirits (vodka, gin, whiskey)', cat: 'drinks', tags: ['alcohol'], serv: [g('1 shot (1.5 oz)', 42)] },
  { q: 'Beverages, Protein powder whey based', name: 'Whey protein powder', cat: 'supplements', tags: ['protein', 'shake', 'protein shake', 'protein powder', 'scoop'], serv: [g('1 scoop', 30), g('2 scoops', 60)] },
  { q: 'Beverages, Whey protein powder isolate', name: 'Whey protein isolate', cat: 'supplements', tags: ['protein', 'shake'], serv: [g('1 scoop', 30)] },
  { q: 'Beverages, Protein powder soy based', name: 'Soy protein powder', cat: 'supplements', tags: ['protein', 'vegan'], serv: [g('1 scoop', 30)] },
  { q: 'Water, bottled, generic', name: 'Water', cat: 'drinks', tags: [], serv: [g('1 glass', 240), g('1 bottle (500 mL)', 500)] },
  // ---- snacks & sweets ------------------------------------------------------------------------
  { q: 'Chocolate, dark, 70-85% cacao solids', name: 'Dark chocolate, 70–85%', cat: 'snacks', tags: ['chocolate'], serv: [g('2 squares', 20), g('1 bar', 100)] },
  { q: 'Candies, milk chocolate', name: 'Milk chocolate', cat: 'snacks', tags: ['chocolate', 'candy'], serv: [g('1 bar (1.55 oz)', 44)] },
  { q: 'Cookies, chocolate chip, commercially prepared, regular, higher fat, enriched', alt: 'Cookies, chocolate chip, commercially prepared', name: 'Chocolate chip cookie', cat: 'snacks', tags: ['cookie', 'dessert'], serv: [g('1 cookie', 16), g('1 large cookie', 40)] },
  { q: 'Snacks, potato chips, plain, salted', name: 'Potato chips', cat: 'snacks', tags: ['chips'], serv: [g('1 oz (about 15 chips)', 28), g('small bag', 42)] },
  { q: 'Snacks, tortilla chips, plain, white corn, salted', alt: 'Snacks, tortilla chips, plain', name: 'Tortilla chips', cat: 'snacks', tags: ['chips'], serv: [g('1 oz (about 10 chips)', 28)] },
  { q: 'Snacks, popcorn, air-popped', name: 'Popcorn, air-popped', cat: 'snacks', tags: [], serv: [g('3 cups', 24), g('1 cup', 8)] },
  { q: 'Snacks, pretzels, hard, plain, salted', name: 'Pretzels', cat: 'snacks', tags: [], serv: [g('1 oz', 28)] },
  { q: 'Snacks, granola bars, soft, uncoated, chocolate chip', alt: 'Snacks, granola bars, soft', name: 'Granola bar', cat: 'snacks', tags: ['bar'], serv: [g('1 bar', 28)] },
  { q: 'Snacks, trail mix, regular', name: 'Trail mix', cat: 'snacks', tags: ['nuts'], serv: [g('¼ cup', 38), g('1 oz', 28)] },
  { q: 'Cake, chocolate, commercially prepared with chocolate frosting', name: 'Chocolate cake', cat: 'snacks', tags: ['dessert', 'cake'], serv: [g('1 slice', 64)] },
  { q: 'Doughnuts, yeast-leavened, glazed, enriched (includes honey buns)', alt: 'Doughnuts, yeast-leavened, glazed', name: 'Glazed doughnut', cat: 'snacks', tags: ['dessert', 'breakfast'], serv: [g('1 doughnut', 60)] },
  { q: 'Muffins, blueberry, commercially prepared (Includes mini-muffins)', alt: 'Muffins, blueberry, commercially prepared', name: 'Blueberry muffin', cat: 'snacks', tags: ['breakfast'], serv: [g('1 muffin', 113)] },
  { q: 'Puddings, chocolate, ready-to-eat', name: 'Chocolate pudding', cat: 'snacks', tags: ['dessert'], serv: [g('1 cup', 142)] },
  // ---- meals & fast food ----------------------------------------------------------------------
  { q: 'Fast foods, hamburger; single, regular patty; plain', alt: 'Fast foods, hamburger', name: 'Hamburger, fast food', cat: 'prepared', tags: ['burger', 'fast food'], serv: [g('1 sandwich', 90)] },
  { q: 'Fast foods, cheeseburger; single, regular patty; plain', alt: 'Fast foods, cheeseburger', name: 'Cheeseburger, fast food', cat: 'prepared', tags: ['burger', 'fast food'], serv: [g('1 sandwich', 102)] },
  { q: 'Fast foods, chicken, breaded and fried, boneless pieces, plain', alt: 'Fast foods, chicken, breaded and fried', name: 'Chicken nuggets', cat: 'prepared', tags: ['chicken', 'fast food'], serv: [g('6 pieces', 96), g('10 pieces', 160)] },
  { q: 'Fast foods, potato, french fried in vegetable oil', name: 'French fries', cat: 'prepared', tags: ['potato', 'fast food'], serv: [g('small', 71), g('medium', 117), g('large', 154)] },
  { q: 'Pizza, cheese topping, regular crust, frozen, cooked', alt: 'Pizza, cheese topping, regular crust', name: 'Cheese pizza', cat: 'prepared', tags: ['pizza'], serv: [g('1 slice', 107), g('2 slices', 214)] },
  { q: 'Pizza, pepperoni topping, regular crust, frozen, cooked', alt: 'Pizza, pepperoni topping, regular crust', name: 'Pepperoni pizza', cat: 'prepared', tags: ['pizza'], serv: [g('1 slice', 111), g('2 slices', 222)] },
  { q: 'Fast foods, taco with beef, cheese and lettuce, hard shell', alt: 'Fast foods, taco', name: 'Beef taco', cat: 'prepared', tags: ['mexican', 'fast food'], serv: [g('1 taco', 102), g('2 tacos', 204)] },
  { q: 'Fast Foods, burrito, with beans and cheese', alt: 'Fast foods, burrito', name: 'Bean and cheese burrito', cat: 'prepared', tags: ['mexican'], serv: [g('1 burrito', 186)] },
  { q: 'Fast foods, submarine sandwich, turkey, roast beef and ham on white bread with lettuce and tomato', alt: 'Fast foods, submarine sandwich', name: 'Sub sandwich', cat: 'prepared', tags: ['sandwich'], serv: [g('6-inch sub', 228)] },
  { q: 'Soup, chicken noodle, canned, condensed', name: 'Chicken noodle soup', cat: 'prepared', tags: ['soup'], serv: [g('1 cup prepared', 241)] },
  { q: 'Macaroni and cheese, canned entree', alt: 'Macaroni and cheese', name: 'Macaroni and cheese', cat: 'prepared', tags: ['pasta'], serv: [g('1 cup', 252)] },
  { q: 'Fast foods, fish sandwich, with tartar sauce', name: 'Fish sandwich, fast food', cat: 'prepared', tags: ['fast food'], serv: [g('1 sandwich', 158)] },
  { q: 'Fast foods, egg, scrambled', alt: 'Fast foods, biscuit, with egg', name: 'Fast-food scrambled eggs', cat: 'prepared', tags: ['breakfast', 'fast food'], serv: [g('2 eggs', 94)] },
];
